### ISSUE TITLE
UnicodeEncodeError in PSLiteral

### ISSUE THREAD

**Issue by garabik** [euske/pdfminer#114]
I have one file where the extraction crashes (when debug is on):

```
$ pdf2txt.py -d file.pdf 
Traceback (most recent call last):
  File "/usr/local/bin/pdf2txt.py", line 116, in <module>
    if __name__ == '__main__': sys.exit(main(sys.argv))
  File "/usr/local/bin/pdf2txt.py", line 108, in main
    caching=caching, check_extractable=True):
  File "/usr/local/lib/python2.7/dist-packages/pdfminer/pdfpage.py", line 122, in get_pages
    doc = PDFDocument(parser, password=password, caching=caching)
  File "/usr/local/lib/python2.7/dist-packages/pdfminer/pdfdocument.py", line 564, in __init__
    xref.load(parser)
  File "/usr/local/lib/python2.7/dist-packages/pdfminer/pdfdocument.py", line 189, in load
    (_, obj) = parser.nextobject()
  File "/usr/local/lib/python2.7/dist-packages/pdfminer/psparser.py", line 574, in nextobject
    (pos, token) = self.nexttoken()
  File "/usr/local/lib/python2.7/dist-packages/pdfminer/psparser.py", line 503, in nexttoken
    logging.debug('nexttoken: %r' % (token,))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 5: ordinal not in range(128)
```

The fix:

```diff
--- psparser.py.old	2015-07-30 09:10:18.087121250 +0200
+++ psparser.py	2015-07-30 09:10:24.671121114 +0200
@@ -60,7 +60,7 @@
         return
 
     def __repr__(self):
-        return '/%s' % self.name
+        return '/%r' % self.name
```

**Comment by euske** [comment]
Patch applied. Thanks.
