### ISSUE TITLE
UnicodeDecodeError when trying `-t tag`

### ISSUE THREAD

**Issue by ArchieT** [euske/pdfminer#136]
PDF: http://isap.sejm.gov.pl/DetailsServlet?id=WDU20130001047

```
 mf  ~  pdf2txt.py -t tag Downloads/D20131047.pdf 
<page id="0" bbox="0.000,0.000,595.276,841.890" rotate="0"><PlacedPDF></PlacedPDF>DZIENNIK USTAWRZECZYPOSPOLITEJ  POLSKIEJWarszawa, dnia 9 września 2013 r.Poz. 1047USTAWAzTraceback (most recent call last):
  File "/usr/bin/pdf2txt.py", line 115, in <module>
    if __name__ == '__main__': sys.exit(main(sys.argv))
  File "/usr/bin/pdf2txt.py", line 109, in main
    interpreter.process_page(page)
  File "/usr/lib/python2.7/site-packages/pdfminer/pdfinterp.py", line 832, in process_page
    self.render_contents(page.resources, page.contents, ctm=ctm)
  File "/usr/lib/python2.7/site-packages/pdfminer/pdfinterp.py", line 845, in render_contents
    self.execute(list_value(streams))
  File "/usr/lib/python2.7/site-packages/pdfminer/pdfinterp.py", line 870, in execute
    func(*args)
  File "/usr/lib/python2.7/site-packages/pdfminer/pdfinterp.py", line 666, in do_BDC
    self.device.begin_tag(tag, props)
  File "/usr/lib/python2.7/site-packages/pdfminer/pdfdevice.py", line 167, in begin_tag
    in sorted(props.iteritems()))
  File "/usr/lib/python2.7/site-packages/pdfminer/pdfdevice.py", line 166, in <genexpr>
    s = ''.join(' %s="%s"' % (enc(k), enc(str(v))) for (k, v)
  File "/usr/lib/python2.7/site-packages/pdfminer/utils.py", line 227, in enc
    return x.encode(codec, 'xmlcharrefreplace')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfe in position 0: ordinal not in range(128)
 mf  ~  1  
```

HTML, text and XML outputs return no errors.

**Comment by longbowking** [comment]
did you find a solution to fix this issue?
