### ISSUE TITLE
TypeError in decode in pdftypes

### ISSUE THREAD

**Issue by sleepyzealot** [euske/pdfminer#175]
I just ran into this error while parsing a PDF.

~~~~
Traceback (most recent call last):
  File ".\pdfminer\pdfinterp.py", line 839, in process_page
    self.render_contents(page.resources, page.contents, ctm=ctm)
  File ".\pdfminer\pdfinterp.py", line 850, in render_contents
    self.init_resources(resources)
  File ".\pdfminer\pdfinterp.py", line 356, in init_resources
    self.fontmap[fontid] = self.rsrcmgr.get_font(objid, spec)
  File ".\pdfminer\pdfinterp.py", line 204, in get_font
    font = self.get_font(None, subspec)
  File ".\pdfminer\pdfinterp.py", line 195, in get_font
    font = PDFCIDFont(self, spec)
  File ".\pdfminer\pdffont.py", line 665, in __init__
    BytesIO(self.fontfile.get_data()))
  File ".\pdfminer\pdftypes.py", line 292, in get_data
    self.decode()
  File ".\pdfminer\pdftypes.py", line 273, in decode
    if 'Predictor' in params:
TypeError: argument of type 'NoneType' is not iterable
~~~~
I found that if I insert:

~~~~
if params==None:
    continue
~~~~

In line 273 resolves the error. It appears that somehow `params` is being set to `None` and this is breaking the `in` function.

**Comment by kaangoksal** [comment]
Just encountered this problem today, I also edited the file as you did. It worked fine after that. Thanks a lot for this post!

**Comment by ghost** [comment]
Woww it worked bro..Thanks alot.
for those who didn't understand:
1.Click on the error (ie double click on "File ".\pdfminer\pdftypes.py", line 273, in decode")
2.it will take you to another file(called pdftypes.py)
3.go to 273 line 
4.Then paste this code at 273rd line
     if params==None:
     continue
(remember don't delete any code written in pdftypes.py...Just add some space to insert above code on 273rd line)

**Comment by sleepyzealot** [comment]
Hey guys, if you're still having trouble with this I suggest switching to the pdfminer.six package. This issue is resolved in that fork.

**Comment by trchavan** [comment]
> Hey guys, if you're still having trouble with this I suggest switching to the pdfminer.six package. This issue is resolved in that fork.

Using pdfminer.six only, still facing the issue

**Comment by reema-dass26** [comment]
hI i am facing error wrt PDFObjref, Can anyone help me decode this?
