### ISSUE TITLE
Exception when parsing outline with special character

### ISSUE THREAD

**Issue by d-sun** [euske/pdfminer#193]
When there is a special character in the outline such as ± (decimal 0177,  0xB1), exception is raised.

Traceback (most recent call last):
 File "\pdf\pdf_tools.py", line 56, in load_pdf
   for (level, title, dest, a, strsuctelem) in document.get_outlines():
 File "lib\site-packages\pdfminer3k-1.3.0-py3.4.egg\pdfminer\pdfparser.py", line 580, in search
   for x in search(entry['First'], level+1):
 File "lib\site-packages\pdfminer3k-1.3.0-py3.4.egg\pdfminer\pdfparser.py", line 583, in search
   for x in search(entry['Next'], level):
 File "lib\site-packages\pdfminer3k-1.3.0-py3.4.egg\pdfminer\pdfparser.py", line 583, in search
   for x in search(entry['Next'], level):
 File "lib\site-packages\pdfminer3k-1.3.0-py3.4.egg\pdfminer\pdfparser.py", line 583, in search
   for x in search(entry['Next'], level):
 File "lib\site-packages\pdfminer3k-1.3.0-py3.4.egg\pdfminer\pdfparser.py", line 583, in search
   for x in search(entry['Next'], level):
 File "lib\site-packages\pdfminer3k-1.3.0-py3.4.egg\pdfminer\pdfparser.py", line 583, in search
   for x in search(entry['Next'], level):
 File "lib\site-packages\pdfminer3k-1.3.0-py3.4.egg\pdfminer\pdfparser.py", line 583, in search
   for x in search(entry['Next'], level):
 File "lib\site-packages\pdfminer3k-1.3.0-py3.4.egg\pdfminer\pdfparser.py", line 583, in search
   for x in search(entry['Next'], level):
 File "lib\site-packages\pdfminer3k-1.3.0-py3.4.egg\pdfminer\pdfparser.py", line 583, in search
   for x in search(entry['Next'], level):
 File "lib\site-packages\pdfminer3k-1.3.0-py3.4.egg\pdfminer\pdfparser.py", line 574, in search
   title = decode_text(str_value(entry['Title']))
 File "lib\site-packages\pdfminer3k-1.3.0-py3.4.egg\pdfminer\utils.py", line 219, in decode_text
   if s.startswith('\xfe\xff'):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str

**Comment by solozyf** [comment]
I encountered a similar issue when I extract the table of content from PDF files. Do you figure out the solution?
