### ISSUE TITLE
Error with PSKeyword

### ISSUE THREAD

**Issue by Afe95** [euske/pdfminer#244]
I am trying to open this PDF file https://akademiasmaku.pl/przepis/pobierz-pdf/772

The code is:

```
content = requests.get('https://akademiasmaku.pl/przepis/pobierz-pdf/772', allow_redirects=True, verify=False, timeout=60).content
stream = BytesIO(content)
parser = PDFParser(stream)
document = PDFDocument(parser, '')
rsrcmgr = PDFResourceManager()
device = PDFDevice(rsrcmgr)
interpreter = PDFPageInterpreter(rsrcmgr, device)
for page in PDFPage.create_pages(document):
    interpreter.process_page(page)
```

In Python 2.7 I get this error:

```
Traceback (most recent call last):
  File "lpdfx/backends.py", line 125, in __init__
    interpreter.process_page(page)
  File ".venv2/local/lib/python2.7/site-packages/pdfminer/pdfinterp.py", line 839, in process_page
    self.render_contents(page.resources, page.contents, ctm=ctm)
  File ".venv2/local/lib/python2.7/site-packages/pdfminer/pdfinterp.py", line 852, in render_contents
    self.execute(list_value(streams))
  File ".venv2/local/lib/python2.7/site-packages/pdfminer/pdfinterp.py", line 877, in execute
    func(*args)
  File ".venv2/local/lib/python2.7/site-packages/pdfminer/pdfinterp.py", line 760, in do_TJ
    self.device.render_string(self.textstate, seq)
  File ".venv2/local/lib/python2.7/site-packages/pdfminer/pdfdevice.py", line 82, in render_string
    scaling, charspace, wordspace, rise, dxscale)
  File ".venv2/local/lib/python2.7/site-packages/pdfminer/pdfdevice.py", line 94, in render_string_horizontal
    for cid in font.decode(obj):
  File ".venv2/local/lib/python2.7/site-packages/pdfminer/pdffont.py", line 714, in decode
    return self.cmap.decode(bytes)
  File ".venv2/local/lib/python2.7/site-packages/pdfminer/cmapdb.py", line 127, in decode
    if len(code) % 2 != 0:
TypeError: object of type 'PSKeyword' has no len()
```

I have tried to Google the error or look at pdfminer3k, but there are no fixes. How should the length of PSKeyword be calculated?

**Comment by mkmanjula96bigdata24cross7** [comment]
yeah same error!!  couldn't figure out the issue

**Comment by mkmanjula96bigdata24cross7** [comment]
Formatting issue with PDF!!

**Comment by sutharketan** [comment]
I am getting the same error, can anyone please help?
