### ISSUE TITLE
20191016 installation fails

### ISSUE THREAD

**Issue by CrimsonGlory** [euske/pdfminer#257]
20191010 worked fine, but 20191016 started to fail when doing pip install (for python 2.7)

```
  Building wheel for pdfminer (setup.py): started
  Building wheel for pdfminer (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jMq_vz/pdfminer/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jMq_vz/pdfminer/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-VfOvnF --python-tag cp27
       cwd: /tmp/pip-install-jMq_vz/pdfminer/
  Complete output (68 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/pdfminer
  copying pdfminer/cmapdb.py -> build/lib/pdfminer
  copying pdfminer/rijndael.py -> build/lib/pdfminer
  copying pdfminer/pdfparser.py -> build/lib/pdfminer
  copying pdfminer/converter.py -> build/lib/pdfminer
  copying pdfminer/glyphlist.py -> build/lib/pdfminer
  copying pdfminer/pdffont.py -> build/lib/pdfminer
  copying pdfminer/arcfour.py -> build/lib/pdfminer
  copying pdfminer/psparser.py -> build/lib/pdfminer
  copying pdfminer/runlength.py -> build/lib/pdfminer
  copying pdfminer/pdftypes.py -> build/lib/pdfminer
  copying pdfminer/fontmetrics.py -> build/lib/pdfminer
  copying pdfminer/__init__.py -> build/lib/pdfminer
  copying pdfminer/latin_enc.py -> build/lib/pdfminer
  copying pdfminer/layout.py -> build/lib/pdfminer
  copying pdfminer/pdfdevice.py -> build/lib/pdfminer
  copying pdfminer/utils.py -> build/lib/pdfminer
  copying pdfminer/image.py -> build/lib/pdfminer
  copying pdfminer/pdfdocument.py -> build/lib/pdfminer
  copying pdfminer/encodingdb.py -> build/lib/pdfminer
  copying pdfminer/pdfcolor.py -> build/lib/pdfminer
  copying pdfminer/pdfpage.py -> build/lib/pdfminer
  copying pdfminer/ccitt.py -> build/lib/pdfminer
  copying pdfminer/lzw.py -> build/lib/pdfminer
  copying pdfminer/pdfinterp.py -> build/lib/pdfminer
  copying pdfminer/ascii85.py -> build/lib/pdfminer
  running build_scripts
  creating build/scripts-2.7
  copying and adjusting tools/pdf2txt.py -> build/scripts-2.7
  copying and adjusting tools/dumppdf.py -> build/scripts-2.7
  changing mode of build/scripts-2.7/pdf2txt.py from 644 to 755
  changing mode of build/scripts-2.7/dumppdf.py from 644 to 755
  installing to build/bdist.linux-x86_64/wheel
  running install
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-jMq_vz/pdfminer/setup.py", line 71, in <module>
      'Topic :: Text Processing',
    File "/usr/local/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/local/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 228, in run
      self.run_command('install')
    File "/usr/local/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-jMq_vz/pdfminer/setup.py", line 11, in run
      from pdfminer.cmapdb import convert_cmap
    File "pdfminer/cmapdb.py", line 22, in <module>
      from .psparser import PSStackParser
    File "pdfminer/psparser.py", line 4, in <module>
      from .utils import choplist
    File "pdfminer/utils.py", line 219, in <module>
      0x00f8, 0x00f9, 0x00fa, 0x00fb, 0x00fc, 0x00fd, 0x00fe, 0x00ff,
    File "pdfminer/utils.py", line 187, in <genexpr>
      PDFDocEncoding = ''.join(chr(x) for x in (
  ValueError: chr() arg not in range(256)
  ----------------------------------------
  ERROR: Failed building wheel for pdfminer
  Running setup.py clean for pdfminer

```

**Comment by vstoykov** [comment]
If you see the [README](https://github.com/euske/pdfminer/blob/master/README.md) it says:
> Warning: Starting from version 20191010, PDFMiner supports Python 3 only.
