### ISSUE TITLE
  Unsupported operand type(s) for +: 'PDFObjRef' and 'bytes'

### ISSUE THREAD

**Issue by adarsa** [euske/pdfminer#258]
When using pdf2txt in PDFPageInterpreter getting the following error. 
```
Traceback (most recent call last):
  File "/Users/adarsa/ilimi/pyenv36/bin/pdf2txt.py", line 115, in <module>
    if __name__ == '__main__': sys.exit(main(sys.argv))
  File "/Users/adarsa/ilimi/pyenv36/bin/pdf2txt.py", line 110, in main
    interpreter.process_page(page)
  File "/Users/adarsa/ilimi/pyenv36/lib/python3.6/site-packages/pdfminer/pdfinterp.py", line 841, in process_page
    self.render_contents(page.resources, page.contents, ctm=ctm)
  File "/Users/adarsa/ilimi/pyenv36/lib/python3.6/site-packages/pdfminer/pdfinterp.py", line 852, in render_contents
    self.init_resources(resources)
  File "/Users/adarsa/ilimi/pyenv36/lib/python3.6/site-packages/pdfminer/pdfinterp.py", line 356, in init_resources
    self.fontmap[fontid] = self.rsrcmgr.get_font(objid, spec)
  File "/Users/adarsa/ilimi/pyenv36/lib/python3.6/site-packages/pdfminer/pdfinterp.py", line 204, in get_font
    font = self.get_font(None, subspec)
  File "/Users/adarsa/ilimi/pyenv36/lib/python3.6/site-packages/pdfminer/pdfinterp.py", line 195, in get_font
    font = PDFCIDFont(self, spec)
  File "/Users/adarsa/ilimi/pyenv36/lib/python3.6/site-packages/pdfminer/pdffont.py", line 641, in __init__
    self.cidcoding = (self.cidsysteminfo.get('Registry', 'unknown') + b'-' +
TypeError: unsupported operand type(s) for +: 'PDFObjRef' and 'bytes'
```

**Comment by euske** [comment]
Hey, thanks for reporting! I attempted to fix the bug in the latest version. Can you try it?
