### ISSUE TITLE
jpeg2000 support

### ISSUE THREAD

**Issue by clach04** [euske/pdfminer#266]
Attempting to extract images from a PDF that contains jpeg200 (aka jp2) bitmaps fails with:

    Traceback (most recent call last):
      File "pdf2txt.py", line 115, in <module>
        if __name__ == '__main__': sys.exit(main(sys.argv))
      File "pdf2txt.py", line 110, in main
        interpreter.process_page(page)
      File "C:\code\py\pdf\pdfminer_clach04\pdfminer\pdfinterp.py", line 842, in process_page
        self.device.end_page(page)
      File "C:\code\py\pdf\pdfminer_clach04\pdfminer\converter.py", line 50, in end_page
        self.receive_layout(self.cur_item)
      File "C:\code\py\pdf\pdfminer_clach04\pdfminer\converter.py", line 387, in receive_layout
        render(ltpage)
      File "C:\code\py\pdf\pdfminer_clach04\pdfminer\converter.py", line 343, in render
        render(child)
      File "C:\code\py\pdf\pdfminer_clach04\pdfminer\converter.py", line 352, in render
        render(child)
      File "C:\code\py\pdf\pdfminer_clach04\pdfminer\converter.py", line 355, in render
        self.place_image(item, 1, item.x0, item.y1, item.width, item.height)
      File "C:\code\py\pdf\pdfminer_clach04\pdfminer\converter.py", line 277, in place_image
        name = self.imagewriter.export_image(item)
      File "C:\code\py\pdf\pdfminer_clach04\pdfminer\image.py", line 120, in export_image
        fp.write(stream.get_data())
      File "C:\code\py\pdf\pdfminer_clach04\pdfminer\pdftypes.py", line 292, in get_data
        self.decode()
      File "C:\code\py\pdf\pdfminer_clach04\pdfminer\pdftypes.py", line 271, in decode
        raise PDFNotImplementedError('Unsupported filter: %r' % f)
    pdfminer.pdftypes.PDFNotImplementedError: Unsupported filter: /'JPXDecode'

Test is the same as in issue #264. NOTE that needs the fix for #264 to be applied.

**Comment by clach04** [comment]
I tried the dumb/obviously thing to no do anything (like the way jpeg is handled) with *no* success :(

    +            elif f == LIT('JPXDecode'):
    +                # not yet..
    +                print('faking JPXDecode')
    +                pass  # fake it

the images files it dumps don;t appear to be in any file format I can recognize (and they are not in jp2 file format at this point). However this hack does at least mean the text can be extracted with an idea as to which file is at which location.
