### ISSUE TITLE
Error installing pdfminer

### ISSUE THREAD

**Issue by shoron-dutta** [euske/pdfminer#291]
Hi,
I am using Ubuntu 19.10

While trying the command: sudo pip install pdfminer

I have faced the following error:

"/usr/bin/python -u -c "import setuptools, tokenize;file='/tmp/pip-install-KAd0kh/pdfminer/setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" install --record /tmp/pip-record-N1BtXX/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-KAd0kh/pdfminer/

The trace is:

Failed building wheel for pdfminer
  Running setup.py clean for pdfminer
Failed to build pdfminer
Installing collected packages: pdfminer
  Running setup.py install for pdfminer ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-zlGLyp/pdfminer/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-2xQmbY/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-zlGLyp/pdfminer/setup.py", line 71, in <module>
        'Topic :: Text Processing',
      File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-zlGLyp/pdfminer/setup.py", line 11, in run
        from pdfminer.cmapdb import convert_cmap
      File "pdfminer/cmapdb.py", line 22, in <module>
        from .psparser import PSStackParser
      File "pdfminer/psparser.py", line 4, in <module>
        from .utils import choplist
      File "pdfminer/utils.py", line 219, in <module>
        0x00f8, 0x00f9, 0x00fa, 0x00fb, 0x00fc, 0x00fd, 0x00fe, 0x00ff,
      File "pdfminer/utils.py", line 187, in <genexpr>
        PDFDocEncoding = ''.join(chr(x) for x in (
    ValueError: chr() arg not in range(256)

**Comment by shoron-dutta** [comment]
Fixed by running with pip3.
