### ISSUE TITLE
KeyError: 'Resources' on some files

### ISSUE THREAD

**Issue by PonteIneptique** [euske/pdfminer#56]
You can find the file [here](https://www.dropbox.com/s/zllzxr5dngs0hsc/impius%20-%20orumPatres1.pdf)

``` python
from pdfminer.pdfparser import PDFParser
from pdfminer.pdfdocument import PDFDocument
from pdfminer.pdfpage import PDFPage
from pdfminer.pdfpage import PDFTextExtractionNotAllowed
from pdfminer.pdfinterp import PDFResourceManager
from pdfminer.pdfinterp import PDFPageInterpreter
from pdfminer.pdfdevice import PDFDevice

fp = open('impius - orumPatres1.pdf', 'rb')

parser = PDFParser(fp)
document = PDFDocument(parser, password)
if not document.is_extractable:
    raise PDFTextExtractionNotAllowed
rsrcmgr = PDFResourceManager()
device = PDFDevice(rsrcmgr)
interpreter = PDFPageInterpreter(rsrcmgr, device)
for page in PDFPage.create_pages(document):
    interpreter.process_page(page)
```

Result : 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jc/.virtualenvs/pdfquery/lib/python2.7/site-packages/pdfminer/pdfpage.py", line 100, in create_pages
    yield klass(document, objid, tree)
  File "/Users/jc/.virtualenvs/pdfquery/lib/python2.7/site-packages/pdfminer/pdfpage.py", line 52, in __init__
    self.resources = resolve1(self.attrs['Resources'])
KeyError: 'Resources'
```

**Comment by mplessard** [comment]
I've got a similar error but on MediaBox...
```
Traceback (most recent call last):
  File "C:/Users/lesmp/Documents/scripts/RBC_pdf_to_excel/pdf_to_excel.py", line 20, in <module>
    for page_number, page in enumerate(PDFPage.create_pages(document)):
  File "C:\Users\lesmp\AppData\Local\Programs\Python\Python35\lib\site-packages\pdfminer\pdfpage.py", line 109, in create_pages
    yield klass(document, objid, obj)
  File "C:\Users\lesmp\AppData\Local\Programs\Python\Python35\lib\site-packages\pdfminer\pdfpage.py", line 55, in __init__
    self.mediabox = resolve1(self.attrs['MediaBox'])
KeyError: 'MediaBox'
```

**Comment by tderouin** [comment]
I've experienced a similar error with the latest version:

Traceback (most recent call last):
  File "/usr/local/bin/pdf2txt.py", line 116, in <module>
    if __name__ == '__main__': sys.exit(main(sys.argv))
  File "/usr/local/bin/pdf2txt.py", line 108, in main
    caching=caching, check_extractable=True):
  File "/usr/local/lib/python2.7/site-packages/pdfminer/pdfpage.py", line 127, in get_pages
    for (pageno, page) in enumerate(klass.create_pages(doc)):
  File "/usr/local/lib/python2.7/site-packages/pdfminer/pdfpage.py", line 101, in create_pages
    yield klass(document, objid, tree)
  File "/usr/local/lib/python2.7/site-packages/pdfminer/pdfpage.py", line 56, in __init__
    self.mediabox = resolve1(self.attrs['MediaBox'])
KeyError: 'MediaBox'

**Comment by dogerpve** [comment]
`def pri():
	import re
	from pdfminer.layout import LAParams
	from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
	from pdfminer.pdfpage import PDFPage
	from pdfminer.converter import TextConverter
	from io import BytesIO
	with open('/tmp/gg.pdf', 'rb') as file:
		retstr = BytesIO()

		rsrcmgr = PDFResourceManager()
		device = TextConverter(rsrcmgr,retstr,laparams=LAParams())
		interpreter = PDFPageInterpreter(rsrcmgr, device)
		for page in PDFPage.get_pages(file, maxpages=0):
			interpreter.process_page(page)
			text = retstr.getvalue()
		device.close()
		retstr.close()
		text_in_pdf = re.sub(r'\s+', ' ', text)
		print unicode(text_in_pdf, 'utf-8')
`
assert
`File "def_save.py", line 39, in <module>
    pri()
  File "def_save.py", line 29, in pri
    interpreter.process_page(page)
  File "/usr/local/lib/python2.7/dist-packages/pdfminer/pdfinterp.py", line 836, in process_page
    self.render_contents(page.resources, page.contents, ctm=ctm)
  File "/usr/local/lib/python2.7/dist-packages/pdfminer/pdfinterp.py", line 848, in render_contents
    self.execute(list_value(streams))
  File "/usr/local/lib/python2.7/dist-packages/pdfminer/pdfinterp.py", line 872, in execute
    func(*args)
  File "/usr/local/lib/python2.7/dist-packages/pdfminer/pdfinterp.py", line 813, in do_Do
    interpreter.render_contents(resources, [xobj], ctm=mult_matrix(matrix, self.ctm))
  File "/usr/local/lib/python2.7/dist-packages/pdfminer/pdfinterp.py", line 846, in render_contents
    self.init_resources(resources)
  File "/usr/local/lib/python2.7/dist-packages/pdfminer/pdfinterp.py", line 352, in init_resources
    self.fontmap[fontid] = self.rsrcmgr.get_font(objid, spec)
  File "/usr/local/lib/python2.7/dist-packages/pdfminer/pdfinterp.py", line 202, in get_font
    font = self.get_font(None, subspec)
  File "/usr/local/lib/python2.7/dist-packages/pdfminer/pdfinterp.py", line 193, in get_font
    font = PDFCIDFont(self, spec)
  File "/usr/local/lib/python2.7/dist-packages/pdfminer/pdffont.py", line 676, in __init__
    self.unicode_map = ttf.create_unicode_map()
  File "/usr/local/lib/python2.7/dist-packages/pdfminer/pdffont.py", line 447, in create_unicode_map
    assert 0
AssertionError
`

**Comment by mohankumarp** [comment]
@euske ,
Ref:  key errors such as KeyError: 'Resources', KeyError: 'MediaBox'
As on 26th Mar 2018, latest version available  is pdfminer==20140328; which do not have the fix. May I know the on which build version the fix would be available that you are referring to?

Mohan

**Comment by PonteIneptique** [comment]
I never came back but thank you @euske and @mohankumarp to have taken the time to support your users ;)
